### ISSUE TITLE
[bug] go-fliecoin deamon crashed when sync blocks

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/go-filecoin#2741]
> my conputer hardware information
* cup: i7 8700k
* ram: 48GB

It's crashed after i had run `go-filecoin mining start` command about 10 hours. 
Is it because be proposed many storage deals?

Buy the miner's storage power is not increase. https://stats.kittyhawk.wtf/storage/mining

My peer ID: QmdnDLtroyqkPQBk8NuTEyoBY9iPgaa2D4wt4fyDMHAewK
```
}] (apply message failed: nonce too low) ^[[0;37mblock_generate.go:97^[[0m
11387368 ^[[0;37m04:48:54.970  INFO ^[[0;34m    mining: ^[[0mpermanent ApplyMessage failure, [SignedMessage cid=[zDPWYqFD4gDkiXZPp5gv9kHih1qSMXsmSjqLnwhECBFcv         w6LJj44]: {
11387369   "meteredMessage": {
11387370     "message": {
11387371       "to": "t2b2p2ajwuio3a25ykviv3xmrydhccj26m6i5baoa",
11387372       "from": "t1zhm7wuebzw6g7ot4ofrzhcaffmptpadf5tofody",
11387373       "nonce": "25992",
11387374       "value": "0.0000007398752256",
11387375       "method": "createChannel",
11387376       "params": "glUBKzovs5HSZE8j0nGZ9ztku7SVaMRD2NIG"
11387377     },
11387378     "gasPrice": "0",
11387379     "gasLimit": "300"
11387380   },
11387381   "signature": "I0ir2Oh8alEyoPhsGZEN1s0p3Rp5UQzoblspFcXdUYMSupr+x/joPCSyaSEQfJktwTPTXGJLpBYU5+GasZDf3gA="
11387382 }] (apply message failed: nonce too low) ^[[0;37mblock_generate.go:97^[[0m
11387383 fatal error: concurrent map iteration and map write
11387384 
11387385 goroutine 23828 [running]:
11387386 runtime.throw(0x1573205, 0x26)
11387387         /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0b2d33c68 sp=0xc0b2d33c38 pc=0x4dff82
11387388 runtime.mapiternext(0xc0b2d33d48)
11387389         /usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc0b2d33cf0 sp=0xc0b2d33c68 pc=0x4c1777
11387390 github.com/filecoin-project/go-filecoin/core.(*MessagePool).timeoutMessages(0xc0001eeb70, 0x17c5260, 0xc0ae769ec0, 0x7fcd1a3fc210, 0xc0004ba9a0, 0xc0         e59772f0, 0x10f200, 0x153000)
11387391         /go/src/github.com/filecoin-project/go-filecoin/core/message_pool.go:185 +0x203 fp=0xc0b2d33db8 sp=0xc0b2d33cf0 pc=0xbb8183
11387392 github.com/filecoin-project/go-filecoin/core.(*MessagePool).UpdateMessagePool(0xc0001eeb70, 0x17c5260, 0xc0ae769ec0, 0x7fcd1a3fc210, 0xc0004ba9a0, 0x         c047969a40, 0xc0e59772f0, 0x0, 0x0)
11387393         /go/src/github.com/filecoin-project/go-filecoin/core/message_pool.go:155 +0x465 fp=0xc0b2d33ec8 sp=0xc0b2d33db8 pc=0xbb7f25
11387394 github.com/filecoin-project/go-filecoin/node.(*Node).handleNewHeaviestTipSet(0xc0000ac1e0, 0x17c5260, 0xc0ae769ec0, 0xc047969a40, 0xc0ae7c2510)
11387395         /go/src/github.com/filecoin-project/go-filecoin/node/node.go:660 +0x346 fp=0xc0b2d33fb8 sp=0xc0b2d33ec8 pc=0xcc8286
11387396 runtime.goexit()
11387397         /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0b2d33fc0 sp=0xc0b2d33fb8 pc=0x50f521
11387398 created by github.com/filecoin-project/go-filecoin/node.(*Node).Start
11387399         /go/src/github.com/filecoin-project/go-filecoin/node/node.go:543 +0x7f1
11387400 
11387401 goroutine 1 [chan receive, 1029 minutes]:
11387402 github.com/filecoin-project/go-filecoin/commands.runAPIAndWait(0x17c5260, 0xc0002024c0, 0xc0000ac1e0, 0xc00020c1e0, 0xc0001f60e0, 0x0, 0x0)
```

**Comment by anorth** [comment]
Thanks for the report. I think this is the same issue reported in #2485, #263, 2645 and has been fixed on master. Because the 0.1.4 user devnet was built before that fix, you'll observe this problem until then 0.2.x devnet is launched (very soon).

I'll close this issue. Please re-open if you observe it on master or the 0.2 devnet when launched.

**Comment by coder-lb** [comment]
I find this issue still exists in 0.3.2. The commit is 0edc3e9c95f198cc5a20c3f94badb6d86160d7cc.

Please see the corresponding log:
```
fatal error: concurrent map iteration and map write

goroutine 2422388 [running]:
runtime.throw(0x1d9bbbe, 0x26)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc03d4778e8 sp=0xc03d4778b8 pc=0x5bec12
runtime.mapiternext(0xc05dafe420)
        /usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc03d477970 sp=0xc03d4778e8 pc=0x5a0447
reflect.mapiternext(0xc05dafe420)
        /usr/local/go/src/runtime/map.go:1349 +0x2b fp=0xc03d477988 sp=0xc03d477970 pc=0x5a131b
reflect.Value.MapKeys(0x1c2ae20, 0xc04ae9f2c8, 0x195, 0x0, 0xc0d26fdc00, 0x20)
        /usr/local/go/src/reflect/value.go:1150 +0x109 fp=0xc03d477a00 sp=0xc03d477988 pc=0x64c059
encoding/json.mapEncoder.encode(0xc02eae37f0, 0xc0c616f730, 0x1c2ae20, 0xc04ae9f2c8, 0x195, 0x100)
        /usr/local/go/src/encoding/json/encode.go:686 +0x100 fp=0xc03d477b48 sp=0xc03d477a00 pc=0x697d00
encoding/json.mapEncoder.encode-fm(0xc0c616f730, 0x1c2ae20, 0xc04ae9f2c8, 0x195, 0x100)
        /usr/local/go/src/encoding/json/encode.go:678 +0x64 fp=0xc03d477b88 sp=0xc03d477b48 pc=0x6a3b44
encoding/json.structEncoder.encode(0xc009aa4900, 0x2, 0x2, 0xc0c616f730, 0x1cf5300, 0xc04ae9f2c0, 0x199, 0x690100)
        /usr/local/go/src/encoding/json/encode.go:660 +0x304 fp=0xc03d477c28 sp=0xc03d477b88 pc=0x6979d4
encoding/json.structEncoder.encode-fm(0xc0c616f730, 0x1cf5300, 0xc04ae9f2c0, 0x199, 0xc04ae90100)
        /usr/local/go/src/encoding/json/encode.go:631 +0x76 fp=0xc03d477c78 sp=0xc03d477c28 pc=0x6a3ac6
encoding/json.ptrEncoder.encode(0xc02ed08220, 0xc0c616f730, 0x1c82380, 0xc04ae9f2c0, 0x16, 0x1c80100)
        /usr/local/go/src/encoding/json/encode.go:806 +0xb2 fp=0xc03d477cc0 sp=0xc03d477c78 pc=0x698e52
encoding/json.ptrEncoder.encode-fm(0xc0c616f730, 0x1c82380, 0xc04ae9f2c0, 0x16, 0xc03d470100)
        /usr/local/go/src/encoding/json/encode.go:801 +0x64 fp=0xc03d477d00 sp=0xc03d477cc0 pc=0x6a3cc4
encoding/json.(*encodeState).reflectValue(0xc0c616f730, 0x1c82380, 0xc04ae9f2c0, 0x16, 0x2f60100)
        /usr/local/go/src/encoding/json/encode.go:334 +0x82 fp=0xc03d477d38 sp=0xc03d477d00 pc=0x6951a2
encoding/json.(*encodeState).marshal(0xc0c616f730, 0x1c82380, 0xc04ae9f2c0, 0xc03d470100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:306 +0xee fp=0xc03d477d80 sp=0xc03d477d38 pc=0x694c4e
encoding/json.Marshal(0x1c82380, 0xc04ae9f2c0, 0x227, 0xc00a0eb660, 0x1, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:160 +0x52 fp=0xc03d477df8 sp=0xc03d477d80 pc=0x694272
github.com/filecoin-project/go-filecoin/protocol/storage.(*Miner).saveDealsAwaitingSeal(0xc0745bae80, 0x2003460, 0xc085af8ac0)
        /home/fil/src/github.com/filecoin-project/go-filecoin/protocol/storage/miner.go:489 +0x3f fp=0xc03d477e70 sp=0xc03d477df8 pc=0xe008df
github.com/filecoin-project/go-filecoin/protocol/storage.(*Miner).processStorageDeal(0xc0745bae80, 0xc05c321410, 0x26)
        /home/fil/src/github.com/filecoin-project/go-filecoin/protocol/storage/miner.go:469 +0xb82 fp=0xc03d477fc8 sp=0xc03d477e70 pc=0xe003f2
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc03d477fd0 sp=0xc03d477fc8 pc=0x5ee371
created by github.com/filecoin-project/go-filecoin/protocol/storage.acceptProposal
        /home/fil/src/github.com/filecoin-project/go-filecoin/protocol/storage/miner.go:342 +0x213
```
